---
- name: cpy files from local to remote
  hosts: all

  tasks:
    - name: copy files
      become: yes # login as root
      copy:
        src: copy-content.txt
        dest: /home/isuru
        owner: isuru
        group: isuru
        mode: 0644
