---
- name: verify apacehe installatoin
  hosts: localhost
  tasks:
    - name: apache latest verificatiion 
      ansible.builtin.apt:
        name: apache2 
        state: latest

    - name: copy apache config 
      copy:
        src: /tmp/apache2/apache.conf
        dest: /etc/apache2/apache.conf
      notify:
        - restart apache 
      
    - name: ensure apache is running 
      service:
        name: apache2 
        state: started 

      handlers:
        - name: restart apache 
          service:  
            name: apache2
            state: 