---
- name : add user
  hosts : all

  tasks:
    - name: add user using user module
      user:
        name: tony
        home: /home/tony
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
        # at runtime give the password 
        # ansible-playbook playbook.yaml --extra-vars password=Abc@123

    - name: Add tony to Sudoers 
      community.general.sudoers:
        name: tony 
        user: tony
        state: present
        commands: ALL

