---
- name : add user
  hosts : all

  tasks:
    - name: add user using user module
      user:
        name: tony
        home: /home/tony
        shell: /bin/bash

    - name: Add tony to Sudoers 
      community.general.sudoers:
        name: tony 
        user: tony
        state: present
        commands: ALL

