---
- name: download tomcat from internet
  hosts: all

  tasks:
    - name: create a directory 
      file:
        path: /opt/tomcat
        state: directory
        owner: root
        group: root

    - name: dwonload tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
        dest: /opt/tomcat
        mode: 0755
        group: root
        owner: root 