---
- name: play with tags
  hosts: all 
  tasks:
    - name: install apache2 
      ansible.builtin.apt: 
        name: apache2
        state: present
      tags: i-apache2 # these both methods are correct 


    - name: start apache2 
      service:
        name: apache2
        state: started
      tags:
        - s-apache2

# when running give as follows
# ansible-playook pb_main.yaml -t i-pache2

# to get all the tags in a playook.
#  ansible-playbook play_book_name.yaml --list-tags 


# to skip a playbook with specific tags 
# ansible-playbook play_book_name.yaml --skip-tags tag_name

# we can start a playbook at a specific task
# ansible-playbook play_book_name.yaml --start-at-task  task_name